export class ConcentRequestActions {
    static LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
    static FILTER_ITEMS_BY_GROUP = 'FILTER_ITEMS_BY_GROUP';
    static FILTER_ITEMS_BY_GROUP_BY_ITEM = 'FILTER_ITEMS_BY_GROUP_BY_ITEM';
    static SHOW_ITEM_RELATIONS = 'SHOW_ITEM_RELATIONS';
    static SHOW_ITEM_RELATIONS_EXPANDED = 'SHOW_ITEM_RELATIONS_EXPANDED';
    static CLOSE_ITEM_RELATIONS_EXPANDED = 'CLOSE_ITEM_RELATIONS_EXPANDED';
    static ITEM_REQUEST_ACCEPTED = 'ITEM_REQUEST_ACCEPTED';
    static ITEM_REQUEST_REVOKED = 'ITEM_REQUEST_REVOKED';
}
